### ISSUE TITLE
Front-end pre-requisites installation guide

### ISSUE THREAD

**Issue by djtoro** [TORO-IO/hei-workshop#12]

**Comment by pongstr** [comment]
Added guides to installing dev tools pre-requisite for:

- [Windows](https://github.com/TORO-IO/hei-workshop#windows)
- [Ubuntu Linux](https://github.com/TORO-IO/hei-workshop#linux)
- [OSX](https://github.com/TORO-IO/hei-workshop#osx)

Also added: **Getting Started** section on how to clone the repository. This actually goes out to everyone who will be adding their presentation slides. Instructions on how to run Backend/Frontend apps resides in their respective directories.
